/**
 * Resource mapping — defines which resources are in PostgreSQL vs MongoDB.
 *
 * SQL resources use the pg Pool (`/api/<table_name>`).
 * NoSQL resources use the MongoDB driver (`/api/nosql/<collection_name>`).
 */

/** All PostgreSQL tables available as REST resources. */
export const SQL_RESOURCES = new Set([
  'users',
  'roles',
  'permissions',
  'role_permissions',
  'user_role_assignments',
  'user_permissions',
  'user_sessions',
  'oauth_accounts',
  'organizations',
  'organization_members',
  'projects',
  'project_members',
  'workspaces',
  'workspace_members',
  'plans',
  'plan_features',
  'subscriptions',
  'invoices',
  'payments',
  'usage_meters',
  'usage_records',
  'promotions',
  'promotion_plans',
  'collections',
  'fields',
  'field_options',
  'collection_indices',
  'collection_relations',
  'views',
  'view_permissions',
  'dashboards',
  'dashboard_permissions',
  'dashboard_templates',
  'resources',
  'resource_versions',
  'resource_permissions',
  'resource_shares',
  'resource_relations',
  'tags',
  'resource_tags',
  'comments',
  'database_connections',
  'sync_channels',
  'sync_executions',
  'provisioned_databases',
  'adapters',
  'adapter_mappings',
  'adapter_executions',
  'contacts',
  'webhooks',
  'webhook_deliveries',
  'notifications',
  'file_uploads',
  'api_keys',
  'policy_rules',
  'abac_attribute_definitions',
  'abac_rules',
  'abac_rule_groups',
  'abac_rule_group_members',
  'abac_conditions',
  'abac_policies',
  'abac_policy_rule_groups',
  'abac_policy_assignments',
]);

/** All MongoDB collections available as REST resources. */
export const NOSQL_RESOURCES = new Set([
  'collection_records',
  'dashboard_layouts',
  'view_configs',
  'user_preferences',
  'query_cache',
  'workflow_definitions',
  'workflow_executions',
  'global_settings',
  'audit_log',
  'sync_state',
  'connection_credentials',
  'abac_rule_conditions',
  'abac_user_attributes',
]);
